apiServer:
  http:
    host: http://localhost
    port: 9810

renderingServer:
  http:
    host: http://localhost
    port: 9811

ghost:
  port: 6857
  clientSecret:

reporting:
  rollbar:
    enabled: false
    environmentName: 'default'
    accessToken: 'access-token'
